name: 'Build'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        shell: pwsh
        run: |
          dotnet build -c Release

      - name: Install NSIS
        run: |
          apt install nsis