name: 'Build'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        shell: pwsh
        run: |
          dotnet build -c Release

      - name: Install NSIS
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop bucket add extras
          scoop install nsis

      - name: Print NSIS version
        run: makensis -VERSION

      - name: Print NSIS compile flags
        run: makensis -HDRINFO