name: 'Publish Stable'

on:
  release:
    types:
      - "prereleased"
  workflow_dispatch:
    inputs:
      jellyfin_version:
        required: true
        type: string
        description: "The Jellyfin version (eg: 10.8.0-beta1, 10.8.0-beta2)"

jobs:
  publish:
    uses: ./.github/workflows/_meta-publish.yaml
    with:
      jellyfin_version: ${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }}
      server_url: https://repo.jellyfin.org/releases/server/windows/stable-pre/${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }}/combined/jellyfin_${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }}.zip
