name: 'Publish'

on:
  push:
  workflow_dispatch:
    inputs:
      jellyfin:
        required: true
        type: string
        description: "The jellyfin tag"
      type:
        required: true
        type: string
        description: "stable/unstable/stable-pre"

jobs:
  publish:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install NSIS
        run: |
          Invoke-WebRequest 'https://get.scoop.sh' -OutFile 'scoop-install.ps1'
          .\scoop-install.ps1 -RunAsAdmin
          scoop bucket add extras
          scoop install nsis

      - name: Clone UX Repository
        uses: actions/checkout@v3
        with:
          repository: jellyfin/jellyfin-ux
          path: .\jellyfin-ux

      - name: Setup Jellyfin server
        run: |
          Invoke-WebRequest 'https://repo.jellyfin.org/releases/server/windows/stable-pre/10.8.0-beta1/combined/jellyfin_10.8.0-beta1.zip' -OutFile 'jellyfin.zip'
          Expand-Archive 'jellyfin.zip'
          Copy-Item ".\Support Files\LICENSE" -Destination $(Resolve-Path .\jellyfin\jellyfin_*)

      - name: Publish Tray
        run: dotnet publish -c Release -r win-x64 --no-self-contained --output .\jellyfin

      - name: Build installer
        run: |
          $env:InstallLocation = $(Resolve-Path .\jellyfin\jellyfin_*)
          makensis /Dx64 /DUXPATH=$(Resolve-Path .\jellyfin-ux) $(Join-Path -Path $(Resolve-Path .\nsis) -ChildPath jellyfin.nsi)

      - name: Rename Installer
        run: |
          cd .\nsis
          $version = "10.8.0-beta1"
          Rename-Item -Path .\jellyfin_*_windows-x64.exe -NewName ("jellyfin" + $version + "_windows-x64.exe")

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          retention-days: 30
          if-no-files-found: error
          path: .\nsis\jellyfin_*_windows-x64.exe