name: 'Publish'

on:
  push:
  release:
    types:
      - "released"
  workflow_dispatch:
    inputs:
      jellyfin:
        required: true
        type: string
        description: "The Jellyfin version"
      type:
        required: true
        type: choice
        description: "stable/stable-pre"
        options:
          - "stable"
          - "stable-pre"

jobs:
  publish:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Variables
        id: variables
        run: |
          echo "::set-output name=version::10.8.0-beta1"
          echo "::set-output name=type::stable-pre"

      - name: Install NSIS
        run: |
          Invoke-WebRequest 'https://get.scoop.sh' -OutFile 'scoop-install.ps1'
          .\scoop-install.ps1 -RunAsAdmin
          scoop bucket add extras
          scoop install nsis

      - name: Clone UX Repository
        uses: actions/checkout@v3
        with:
          repository: jellyfin/jellyfin-ux
          path: .\jellyfin-ux

      - name: Setup Jellyfin server
        run: |
          Invoke-WebRequest 'https://repo.jellyfin.org/releases/server/windows/${{ steps.variables.type }}/${{ steps.variables.version }}/combined/jellyfin_${{ steps.variables.version }}.zip' -OutFile 'jellyfin.zip'
          Expand-Archive 'jellyfin.zip'
          Copy-Item ".\Support Files\LICENSE" -Destination $(Resolve-Path .\jellyfin\jellyfin_*)

      - name: Publish Tray
        run: dotnet publish -c Release -r win-x64 --no-self-contained --output .\jellyfin

      - name: Build installer
        run: |
          $env:InstallLocation = $(Resolve-Path .\jellyfin\jellyfin_*)
          makensis /Dx64 /DUXPATH=$(Resolve-Path .\jellyfin-ux) $(Join-Path -Path $(Resolve-Path .\nsis) -ChildPath jellyfin.nsi)

      - name: Rename Installer
        run: |
          cd .\nsis
          Rename-Item -Path .\jellyfin_*_windows-x64.exe -NewName ("jellyfin_" + ${{ steps.variables.version }} + "_windows-x64.exe")

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          retention-days: 30
          if-no-files-found: error
          path: .\nsis\jellyfin_*_windows-x64.exe