name: 'Publish Stable-Pre'

on:
  release:
    types:
      - "prereleased"
  workflow_dispatch:
    inputs:
      jellyfin_version:
        required: true
        type: string
        description: "The Jellyfin version (eg: 10.8.0-beta1, 10.8.0-beta2)"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          - echo "${{ ${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }}"
