name: 'Publish Stable'

on:
  release:
    types:
      - "released"
  workflow_dispatch:
    inputs:
      jellyfin_version:
        required: true
        type: string
        description: "The Jellyfin version (eg: 10.8.0, 10.7.7)"

jobs:
  publish:
    uses: ./.github/workflows/_meta-publish.yaml
    with:
      jellyfin_version: ${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }}
#      server_url: https://repo.jellyfin.org/releases/server/windows/stable/combined/jellyfin_${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }}.zip
      server_url: format('https://repo.jellyfin.org/releases/server/windows/stable/combined/jellyfin_{0}.zip', ${{ github.event.release.tag_name || github.event.inputs.jellyfin_version }})

