name: 'Publish'

on:
  push:
  workflow_dispatch:
    inputs:
      jellyfin-tag:
        required: true
        type: string
        description: "The jellyfin tag"
      type:
        required: true
        type: string
        description: "stable/unstable/stable-pre"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build
        shell: pwsh
        run: |
          dotnet build -c Release

      - name: Install NSIS
        run: |
          Invoke-WebRequest 'https://get.scoop.sh' -OutFile 'scoop-install.ps1'
          .\scoop-install.ps1 -RunAsAdmin
          scoop bucket add extras
          scoop install nsis

      - name: Clone UX Repository
        uses: actions/checkout@v3
        with:
          repository: jellyfin/jellyfin-ux
          path: ./jellyfin-ux

      - name: Setup Jellyfin server
        run: |
          Invoke-WebRequest 'https://repo.jellyfin.org/releases/server/windows/stable-pre/10.8.0-beta1/combined/jellyfin_10.8.0-beta1.zip' -OutFile 'jellyfin.zip'
          Expand-Archive 'jellyfin.zip'
          $env:InstallLocation = "D:\a\jellyfin-server-windows\jellyfin-server-windows\jellyfin"

      - name: Publish Tray
        run: dotnet publish -c Release -r win-x64 --no-self-contained --output ./jellyfin

      - name: Build installer
        run: makensis /Dx64 /DUXPATH="D:\a\jellyfin-server-windows\jellyfin-server-windows\jellyfin-ux" "D:\a\jellyfin-server-windows\jellyfin-server-windows\nsis\jellyfin.nsi"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: installer
          retention-days: 30
          if-no-files-found: error
          path: D:\a\jellyfin-server-windows\jellyfin-server-windows\nsis\jellyfin_10.8.0_windows-x64.exe