name: 'Publish Unstable'

on:
  workflow_dispatch:
    inputs:
      jellyfin_version:
        required: true
        type: string
        description: "The Jellyfin version (eg: 20220405.10)"

jobs:
  publish:
    uses: ./.github/workflows/_meta-publish.yaml
    with:
      jellyfin_version: ${{ github.event.inputs.jellyfin_version }}
      server_url: https://repo.jellyfin.org/releases/server/windows/versions/unstable/combined/${{ github.event.inputs.jellyfin_version }}/jellyfin_${{ github.event.inputs.jellyfin_version }}-unstable.zip
